stages:
  - name: Build image
    steps:
      - publishImageConfig:
          dockerfilePath: ./dockerfile
          buildContext: .
          tag: amr-registry-pre.caas.intel.com/pse-pswe-software-ba/autodeployment:nodetest1
          pushRemote: true
          registry: amr-registry-pre.caas.intel.com/pse-pswe-software-ba

  - name: Deploy
    steps:
      - applyYamlConfig:
          path: ./autodeployment.yaml
