apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
  generation: 2
  name: hello-world-webpage-ingress
  namespace: default
spec:
  rules:
  - host: hello-world.idoc.intel.com
    http:
      paths:
      - backend:
          serviceName: hello-world-webpage-service
          servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-webpage-service
  namespace: default
  labels:
    app: hello-world-webpage
spec:
  ports:
  - port: 80
  selector:
    app: hello-world-webpage


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-rancher-deployment
spec:
  selector:
    matchLabels:
      app: node-rancher-deployment
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: node-rancher-deployment
    spec:
      containers:
      - name: node-rancher-deployment
        image: amr-registry-pre.caas.intel.com/pse-pswe-software-ba/autodeployment:NodeRanchertest
        ports:
        - containerPort: 80
