apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
  generation: 2
  name: hello-world-webpage-ingress
  namespace: default
spec:
  rules:
  - host: hello-world.idoc.intel.com
    http:
      paths:
      - backend:
          serviceName: hello-world-webpage-service
          servicePort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-webpage-service
  namespace: default
  labels:
    app: hello-world-webpage
spec:
  ports:
  - port: 80
  selector:
    app: hello-world-webpage


---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hello-world-webpage
  namespace: default
spec:
  selector:
    matchLabels:
      app: hello-world-webpage
  replicas: 2
  template:
    metadata:
      labels:
        app: hello-world-webpage
    spec:
      containers:
      - name: hello-world-webpage
        image: amr-registry.caas.intel.com/owr/ex-httpd:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
